version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - authproxy 
      - app 
  authproxy:
    build: ./auth_proxy
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
  app:
    build: ./app
