version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - authproxy 
  authproxy:
    build: ./auth_proxy
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
